version: '3.5'
services:
  db:
    image: 'mysql:8'
    container_name: 'db'
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "sia"
      MYSQL_ROOT_PASSWORD: "Ge@140019"
    networks:
      - app-network
  
  web:
    build: .
    container_name: web
    command: gunicorn sia.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app-network
  
  nginx:
    build: ./nginx/
    container_name: nginx-alpine
    volumes:
      - staticfiles:/app/static/
    ports:
      - 8008:80
    depends_on:
      - web
    networks:
      - app-network

volumes:
  staticfiles:

networks:
  app-network:
    driver: bridge
